site_name:  Lemme Doc It
site_author: Khushi Sharma
site_description: Technical writing blog by Khushi Sharma that covers various opinion pieces and learnings about crafting quality documentation.
site_url: https://kiko1216.github.io/lemmedocit/
repo_url: https://github.com/Kiko1216/lemmedocit
repo_name: lemmedocit


nav:
  - About: index.md
  - Blog:
    - blog/index.md
  - Contact: contact.md

theme:
  name: material
  custom_dir: overrides
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - navigation.footer
  font:
    text: Montserrat
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: amber
      primary: custom
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: amber
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
    - stylesheets/extra.css


plugins:
  - search
  - blog:
      archive: false
      post_excerpt: required

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Kiko1216/lemmedocit
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/khushi-sharma/
  html_meta:
    - name: robots
      content: index, follow

markdown_extensions:
  - toc:
      permalink: "#"