site_name:  Lemme Doc It
nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md
  - Contact: contact.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico

plugins:
  - search

plugins:
  - blog:
      archive: false
      post_excerpt: required